---
title: "Analysis of Otsb Experiments"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
    
---

```{r include=FALSE}
knitr::opts_chunk$set(echo=FALSE, fig.width=14,fig.height=8)
```

```{r load_dependencies}

library(tidyverse)
library(stringr)

```

```{r load_dataframe}

final_df <- read.csv('final_df.csv')

final_df_unique <- 
  final_df %>%
  distinct(experiment, repeat., mz1_variable, mz1_osmolarity, .keep_all = TRUE)

final_df_unique %>% 
select(experiment, mz1_osmolarity, mz1_max_growth_rate, mz1_max_yield, wt_max_growth_rate, wt_max_yield)
```

```{r set_graph_settings}

graph_theme <- 
  theme_bw() + 
  theme(
    plot.title = element_text(face = "bold", size = 24, hjust = 0.5),
    legend.background = element_rect(fill = "white", size = 4, colour = "white"),
    # legend.justification = c(0, 1),
    # legend.position = c(0, 1),
    axis.ticks = element_line(colour = "grey70", size = 0.3),
    panel.grid.major = element_line(colour = "grey70", size = 0.3),
    panel.grid.minor = element_blank(),
    text=element_text(size=20)
  )

# Colors 
glucose_red <- "#da5552"
glycerol_green <- "#40916c"
mannose_blue <- "#0077b6"
gray_30 <- "darkgray"
black_42 <- "black"
protein_fill <- "#ffb5a7"
RDM_Purple <- "#7b2cbf"

#shapes
nacl_square <- 22
nacl_betaine <- 21
sucrose_diamond <- 23
sucrose_betaine <-24
RDM_triangle <- 25

#Size
shape_size <- 3
stroke_size <- 1.2



#styling
graph_color_scale <-
scale_color_manual(
  breaks = c('M63_Gly_Sucrose_37C_2020-09-10', #1
             'M63_Glu_CAA_Sucrose_30C_2020-09-29', #2
             'M63_Glu_CAA_Sucrose_37C_2020-10-02', #3
             'M63_Gly_Betaine_Sucrose_37C_2020-10-06', #4
             'M63_Glu_CAA_Betaine_Sucrose_37C_2020-10-09', #5
             'M63_Glu_CAA_NaCl_37C_2020-10-13', #6
             'M63_Glu_CAA_Betaine_NaCl_37C_2020-10-19', #7
             'M63_Glu_Sucrose_37C_2020-10-23', #8
             'M63_Glu_Sucrose_42C_2020-10-27', #9
             'M63_Man_Sucrose_37C_2020-10-27', #10
             'RDM_Sucrose_37C_2020-12-04', #11
             'M63_Gly_NaCl_37C_2021-01-19', #12
             'M63_Gly_Betaine_NaCl_37C_2021-01-25', #13
             'M63_Gly_NaCl_37C_2021-02-10', #14
             'M63_Glu_NaCl_37C_2021-02-16', #15
             'M63_Glu_Betaine_NaCl_37C_2021-02-24', #16
             'M63_Glu_NaCl_37C_2021-03-12', #17
             'M63_Gly_NaCl_37C_2021-03-29' #18
             ),
  values=c(glycerol_green, #1
           gray_30, #2
           glucose_red, #3
           glycerol_green, #4
           glucose_red, #5
           glucose_red, #6
           glucose_red, #7
           glucose_red, #8
           black_42, #9
           mannose_blue, #10
           RDM_Purple, #11
           glycerol_green, #12
           glycerol_green, #13
           glycerol_green, #14
           glucose_red, #15
           glucose_red, #16
           glucose_red, #17
           glycerol_green
           )
)


graph_fill_scale <-
scale_fill_manual(
  breaks = c('M63_Gly_Sucrose_37C_2020-09-10', #1
             'M63_Glu_CAA_Sucrose_30C_2020-09-29', #2
             'M63_Glu_CAA_Sucrose_37C_2020-10-02', #3
             'M63_Gly_Betaine_Sucrose_37C_2020-10-06', #4
             'M63_Glu_CAA_Betaine_Sucrose_37C_2020-10-09', #5
             'M63_Glu_CAA_NaCl_37C_2020-10-13', #6
             'M63_Glu_CAA_Betaine_NaCl_37C_2020-10-19', #7
             'M63_Glu_Sucrose_37C_2020-10-23', #8
             'M63_Glu_Sucrose_42C_2020-10-27', #9
             'M63_Man_Sucrose_37C_2020-10-27', #10
             'RDM_Sucrose_37C_2020-12-04', #11
             'M63_Gly_NaCl_37C_2021-01-19', #12
             'M63_Gly_Betaine_NaCl_37C_2021-01-25', #13
             'M63_Gly_NaCl_37C_2021-02-10', #14
             'M63_Glu_NaCl_37C_2021-02-16', #15
             'M63_Glu_Betaine_NaCl_37C_2021-02-24', #16
             'M63_Glu_NaCl_37C_2021-03-12', #17
             'M63_Gly_NaCl_37C_2021-03-29' #18
             ),
  values=c(glycerol_green, #1
           protein_fill, #2
           protein_fill, #3
           glycerol_green, #4
           protein_fill, #5
           protein_fill, #6
           protein_fill, #7
           glucose_red, #8
           black_42, #9
           mannose_blue, #10
           RDM_Purple, #11
           glycerol_green, #12
           glycerol_green, #13
           glycerol_green, #14
           glucose_red, #15
           glucose_red, #16
           glucose_red, #17
           glycerol_green #18
           )
)
  
graph_shape_scale <-
  scale_shape_manual(
    breaks = c('M63_Gly_Sucrose_37C_2020-09-10', #1
             'M63_Glu_CAA_Sucrose_30C_2020-09-29', #2
             'M63_Glu_CAA_Sucrose_37C_2020-10-02', #3
             'M63_Gly_Betaine_Sucrose_37C_2020-10-06', #4
             'M63_Glu_CAA_Betaine_Sucrose_37C_2020-10-09', #5
             'M63_Glu_CAA_NaCl_37C_2020-10-13', #6
             'M63_Glu_CAA_Betaine_NaCl_37C_2020-10-19', #7
             'M63_Glu_Sucrose_37C_2020-10-23', #8
             'M63_Glu_Sucrose_42C_2020-10-27', #9
             'M63_Man_Sucrose_37C_2020-10-27', #10
             'RDM_Sucrose_37C_2020-12-04', #11
             'M63_Gly_NaCl_37C_2021-01-19', #12
             'M63_Gly_Betaine_NaCl_37C_2021-01-25', #13
             'M63_Gly_NaCl_37C_2021-02-10', #14
             'M63_Glu_NaCl_37C_2021-02-16', #15
             'M63_Glu_Betaine_NaCl_37C_2021-02-24', #16
             'M63_Glu_NaCl_37C_2021-03-12', #17
             'M63_Gly_NaCl_37C_2021-03-29' #18
             ),
    values=c(sucrose_diamond, #1
             sucrose_diamond, #2
             sucrose_diamond, #3
             sucrose_betaine, #4
             sucrose_betaine, #5
             nacl_square, #6
             nacl_betaine, #7
             sucrose_diamond, #8
             sucrose_diamond, #9
             sucrose_diamond, #10
             RDM_triangle, #11
             nacl_square, #12
             nacl_betaine, #13
             nacl_square, #14
             nacl_square, #15
             nacl_betaine, #16
             nacl_square, #17
             nacl_square #18
             )
    )

```


```{r Plot1}
#Growth rate y-axis in hours for glucose NACL on x-axis with and without betaine

final_df_unique %>% 
  filter(str_detect(experiment, 'NaCl')) %>% 
  filter(str_detect(experiment, 'Glu')) %>% 
  ggplot(aes(y=MZ1_max_growth_rate, x=osmolarity, color = experiment, shape = experiment, fill = experiment))+
    geom_point(size=shape_size, stroke =stroke_size)+
    
    ggtitle("01 Osmolarity vs Growth Rate for NaCl")+
    xlab("Osmolarity [mOsm]")+
    ylab(expression(paste("Growth rate ", lambda, " (", hour^-1, ")")))+
    graph_theme+
    graph_color_scale+
    graph_fill_scale+
    graph_shape_scale

```


```{r Plot2}
#Growth rate y-axis in hours for glucose Sucrose on x-axis with and without betaine

final_df_unique %>% 
  filter(str_detect(experiment, 'Sucrose')) %>% 
  filter(str_detect(experiment, 'Glu')) %>% 
  filter(str_detect(experiment, '37')) %>% 
  ggplot(aes(y=MZ1_max_growth_rate, x=osmolarity, color = experiment, shape = experiment, fill = experiment))+
    geom_point(size=shape_size, stroke =stroke_size)+
    
    ggtitle("02 Osmolarity vs Growth Rate for Sucrose")+
    xlab("Solute [mM]")+
    ylab(expression(paste("Growth rate ", lambda, " (", hour^-1, ")")))+
    graph_theme+
    graph_color_scale+
    graph_fill_scale+
    graph_shape_scale


```

```{r Plot3}
#like I had in my presentation growth rate on y-axis x-axis osmolarity change colour coding have scatter plot everything put together


final_df_unique %>% 
  filter(str_detect(experiment, 'Glu|Gly|Man')) %>% 
  filter(str_detect(experiment, '37')) %>% 
  ggplot(aes(y=MZ1_max_growth_rate, x=osmolarity, color = experiment, shape = experiment, fill = experiment))+
    geom_point(size=shape_size, stroke =stroke_size)+
    
    ggtitle("03 Osmolarity vs Growth Rate all conditions")+
    xlab("Osmolarity (mOsm)")+
    ylab(expression(paste("Growth rate ", lambda, " (", hour^-1, ")")))+
    graph_theme+
    graph_color_scale+
    graph_fill_scale+
    graph_shape_scale

```

```{r Plot4}
#growth rate on y axis x osmolarity put glycerol, glucose and mannose no betaine  with sucrose shock

final_df_unique %>% 
  filter(str_detect(experiment, 'Sucrose')) %>% 
  filter(str_detect(experiment, 'Glu|Gly|Man')) %>% 
  filter(str_detect(experiment, '37')) %>% 
  filter(str_detect(experiment, 'Betaine', negate = TRUE)) %>% 
  ggplot(aes(y=MZ1_max_growth_rate, x=osmolarity, color = experiment, shape = experiment, fill = experiment))+
    geom_point(size=shape_size, stroke =stroke_size)+
    
    ggtitle("04 concentration vs Growth Rate for sucrose")+
    xlab("concentration solute (mM)")+
    ylab(expression(paste("Growth rate ", lambda, " (", hour^-1, ")")))+
    graph_theme+
    graph_color_scale+
    graph_fill_scale+
    graph_shape_scale

```

```{r Plot4_2}
#growth rate on y axis x osmolarity put glycerol, glucose and mannose no betaine  with sucrose shock

final_df_unique %>% 
  filter(str_detect(experiment, 'NaCl')) %>% 
  filter(str_detect(experiment, 'Glu|Gly|Man')) %>% 
  filter(str_detect(experiment, '37')) %>% 
  filter(str_detect(experiment, 'Betaine', negate = TRUE)) %>% 

  ggplot(aes(y=MZ1_max_growth_rate, x=osmolarity, color = experiment, shape = experiment, fill = experiment))+
    geom_point(size=shape_size, stroke =stroke_size)+
    
    ggtitle("04 concentration vs Growth Rate for NaCl")+
    xlab("concentration solute (mM)")+
    ylab(expression(paste("Growth rate ", lambda, " (", hour^-1, ")")))+
    graph_theme+
    graph_color_scale+
    graph_fill_scale+
    graph_shape_scale

```

```{r Plot5}
#pOtsB-GFP /OD on yaxis x-axis growth-ratefor just 0mm osmolarities mannose, glycerol and glucose with betaine

final_df_unique %>% 
  filter(str_detect(experiment, 'Glu|Gly|Man|RDM')) %>% 
  filter(str_detect(experiment, '37')) %>% 
  filter(str_detect(variable, '0000')) %>% 
  ggplot(aes(y=MZ1_max_gfp, x=MZ1_max_growth_rate, color = experiment, shape = experiment, fill = experiment))+
    geom_point(size=shape_size, stroke =stroke_size)+
  
    ggtitle("05 GFP Expression vs Growth Rate in base Media")+
    ylab(expression(paste("PotsB-GFP ", "(", OD^-1, ")")))+
    xlab(expression(paste("Growth rate ", lambda, " (", hour^-1, ")")))+
    graph_theme+
    graph_color_scale+
    graph_fill_scale+
    graph_shape_scale


```


```{r Plot6}
#pOtsB-GFP /OD on yaxis x-axis growth-ratefor just 0mm osmolarities mannose, glycerol and glucose with betaine

final_df_unique %>% 
  filter(str_detect(experiment, 'Glu|Gly|Man')) %>% 
  filter(str_detect(experiment, '37')) %>% 
  ggplot(aes(y=MZ1_max_gfp, x=MZ1_max_growth_rate, color = experiment, shape = experiment, fill = experiment))+
    geom_point(size=shape_size, stroke =stroke_size)+
  
    ggtitle("06 GFP Expression vs Growth Rate")+
    ylab(expression(paste("PotsB-GFP ", "(", OD^-1, ")")))+
    xlab(expression(paste("Growth rate ", lambda, " (", hour^-1, ")")))+
    graph_theme+
    graph_color_scale+
    graph_fill_scale+
    graph_shape_scale


```

```{r Plot7}

final_df_unique %>% 
  filter(str_detect(experiment, 'Glu|Gly|Man')) %>% 
  filter(str_detect(experiment, '37')) %>% 
  ggplot(aes(y=MZ1_max_gfp, x=osmolarity, color = experiment, shape = experiment, fill = experiment))+
    geom_point(size=shape_size, stroke =stroke_size)+
    
    ggtitle("07 GFP Expression vs Osmolarity")+
    ylab(expression(paste("PotsB-GFP ", "(", OD^-1, ")")))+
    xlab("osmolarity (mOsm)")+

  
    graph_theme+
    graph_color_scale+
    graph_fill_scale+
    graph_shape_scale


```
```{r Plot8}
#8 pOtsB-gfp / OD y-axis maximum yield on y growthrate on x axis

final_df_unique %>% 
  filter(str_detect(experiment, 'Glu|Gly|Man')) %>% 
  ggplot(aes(y=MZ1_max_od, x=MZ1_max_growth_rate, color = experiment, shape = experiment, fill = experiment))+
    geom_point(size=shape_size, stroke =stroke_size)+
    
    ggtitle("08 Max Yield vs Growth Rate")+
    ylab(expression(paste("Max Yield ", "(", OD[600], ")")))+
    xlab(expression(paste("Growth rate ", lambda, " (", hour^-1, ")")))+
    graph_theme+
    graph_color_scale+
    graph_fill_scale+
    graph_shape_scale
```

```{r Plot9}
#9 pOtsB-gfp / OD y-axis maximum yield on y growthrate on x axis

final_df_unique %>% 
  ggplot(aes(y=MZ1_max_od, x=osmolarity, color = experiment, shape = experiment, fill = experiment))+
    geom_point(size=shape_size, stroke =stroke_size)+
    
    ggtitle("09 Max Yield Expression vs Osmolarity")+
    ylab(expression(paste("Max Yield ", "(", OD[600], ")")))+
    xlab("Osmolarity (mOsm)")+

  
    graph_theme+
    graph_color_scale+
    graph_fill_scale+
    graph_shape_scale


```

```{r Plot10}
#10 max yield y axis against total GFP exponential phase

final_df_unique %>% 
    ggplot(aes(y=MZ1_max_od, x=MZ1_max_gfp, color = experiment, shape = experiment, fill = experiment))+
    geom_point(size=shape_size, stroke =stroke_size)+
    
    ggtitle("10 Max Yield vs GFP Expression (exponential)")+
    ylab(expression(paste("Max Yield ", "(", OD[600], ")")))+
    xlab(expression(paste("PotsB-GFP ", "(", OD^-1, ")")))+

    graph_theme+
    graph_color_scale+
    graph_fill_scale+
    graph_shape_scale
```


```{r Plot11}
#10 max yield y-axis against total AUC GFP

final_df_unique %>% 
    ggplot(aes(y=MZ1_max_od, x=MZ1_gfp_AUC, color = experiment, shape = experiment, fill = experiment))+
    geom_point(size=shape_size, stroke =stroke_size)+
    
    ggtitle("11 Max Yield vs GFP Area under Curve")+
    ylab(expression(paste("Max Yield ", "(", OD[600], ")")))+
    xlab(expression(paste("AUC PotsB-GFP ", "(", OD^-1, ")")))+

  
    graph_theme+
    graph_color_scale+
    graph_fill_scale+
    graph_shape_scale

```


```{r Plot12}
#12 pOtsB-gfp / OD y-axis maximum yield on y growthrate on x axis

final_df_unique %>% 
    ggplot(aes(y=wt_max_od, x=wt_max_growth_rate, color = experiment, shape = experiment, fill = experiment))+
    geom_point(size=shape_size, stroke =stroke_size)+
  
    ggtitle("12 Max Yield wt vs Growth Rate wt")+
    ylab(expression(paste("Max Yield for WT", "(", OD[600], ")")))+
    xlab(expression(paste("Growth rate ", lambda, " (", hour^-1, ")")))+

  
    graph_theme+
    graph_color_scale+
    graph_fill_scale+
    graph_shape_scale


```

```{r Plot12-2}
#12 pOtsB-gfp / OD y-axis maximum yield on y growthrate on x axis

final_df_unique %>%
    filter(str_detect(experiment, 'Glu|Gly|Man')) %>% 
    filter(str_detect(experiment, 'NaCl')) %>% 
    ggplot(aes(y=wt_max_od, x=wt_max_growth_rate, color = experiment, shape = experiment, fill = experiment))+
    geom_point(size=shape_size, stroke =stroke_size)+
  
    ggtitle("12/2 Max Yield wt vs Growth Rate wt for NaCl")+
    ylab(expression(paste("Max Yield for WT", "(", OD[600], ")")))+
    xlab(expression(paste("Growth rate ", lambda, " (", hour^-1, ")")))+

  
    graph_theme+
    graph_color_scale+
    graph_fill_scale+
    graph_shape_scale


```


```{r Plot13}

final_df_unique %>% 
    ggplot(aes(y=MZ1_max_growth_rate, x=wt_max_growth_rate, color = experiment, shape = experiment, fill = experiment))+
    geom_point(size=shape_size, stroke =stroke_size)+
    
    ggtitle("13 Growth rate WT vs growth rate MZ1")+
    ylab(expression(paste("Growth rate MZ1 ", lambda, " (", hour^-1, ")")))+
    xlab(expression(paste("Growth rate WT ", lambda, " (", hour^-1, ")")))+
  
    graph_theme+
    graph_color_scale+
    graph_fill_scale+
    graph_shape_scale
```

```{r Plot14}


final_df_unique %>% 
  filter(str_detect(variable, '0000')) %>%
    ggplot(aes(y=MZ1_max_od, x=GrowthRate, color = experiment, shape = experiment, fill = experiment))+
    geom_point(size=shape_size, stroke =stroke_size)+
    geom_point(aes(y=wt_max_od, x=wt_max_growth_rate),size=1.5, stroke =1.5)+
    
    ggtitle("14 Max Yield vs Growthrate 0 condition")+
    ylab(expression(paste("Max Yield", "(", OD[600], ")")))+
    xlab(expression(paste("Growth rate ", lambda, " (", hour^-1, ")")))+

    graph_theme+
    graph_color_scale+
    graph_fill_scale+
    graph_shape_scale

```

```{r Plot18}
#11. grey thirty degrees, 42C black pOTSb/OD growth rate x-axis 


final_df_unique %>% 
  filter(str_detect(experiment, 'Glu|Gly|Man')) %>% 
  ggplot(aes(y=MZ1_max_gfp, x=MZ1_max_growth_rate, color = experiment, shape = experiment, fill = experiment))+
    geom_point(size=shape_size, stroke =stroke_size)+
  
    ggtitle("18 GFP vs growthrate with temperature")+
    ylab(expression(paste("PotsB-GFP ", "(", OD^-1, ")")))+
    xlab(expression(paste("Growth rate ", lambda, " (", hour^-1, ")")))+
    graph_theme+
    graph_color_scale+
    graph_fill_scale+
    graph_shape_scale

  ```


```{r Plot19}

final_df_unique %>% 
  filter(str_detect(experiment, 'Glu|Gly|Man')) %>% 
  ggplot(aes(y=log(MZ1_max_gfp), x=MZ1_max_growth_rate, color = experiment, shape = experiment, fill = experiment))+
    geom_point(size=shape_size, stroke =stroke_size)+
  
    ggtitle("19 log(GFP) vs growthrate with temperature")+
    ylab(expression(paste("PotsB-GFP ", "(", OD^-1, ")")))+
    xlab(expression(paste("Growth rate ", lambda, " (", hour^-1, ")")))+
    graph_theme+
    graph_color_scale+
    graph_fill_scale+
    graph_shape_scale

  ```
  

  ```{r Plot20}

final_df_unique %>% 
  filter(str_detect(experiment, 'Glu|Gly|Man')) %>% 
  filter(str_detect(experiment, 'NaCl')) %>% 
  ggplot(aes(y=log(MZ1_max_gfp), x=MZ1_max_growth_rate, color = experiment, shape = experiment, fill = experiment))+
    geom_point(size=shape_size, stroke =stroke_size)+
  
    ggtitle("19 log(GFP) vs growthrate NaCl")+
    ylab(expression(paste("PotsB-GFP ", "(", OD^-1, ")")))+
    xlab(expression(paste("Growth rate ", lambda, " (", hour^-1, ")")))+
    graph_theme+
    graph_color_scale+
    graph_fill_scale+
    graph_shape_scale

  ```
  
```{r Plot21}

final_df_unique %>% 
  filter(str_detect(experiment, 'Glu|Gly|Man')) %>% 
  filter(str_detect(experiment, 'NaCl')) %>% 
  ggplot(aes(y=MZ1_max_growth_rate, x=lag_time, color = experiment, shape = experiment, fill = experiment))+
    geom_point(size=shape_size, stroke =stroke_size)+
  
    ggtitle("21 lag_phase vs growthrate")+
    xlab("Lag time (hours)")+
    ylab(expression(paste("Growth rate ", lambda, " (", hour^-1, ")")))+
    graph_theme+
    graph_color_scale+
    graph_fill_scale+
    graph_shape_scale
```
